spring:
  application:
    name: cloud-architecture-deploy-demo

  jpa:
    hibernate:
      ddl-auto: validate

  cloud:
    aws:
      region:
        static: ap-northeast-2
      s3:
        bucket: sdd-momo-s3
        base-url: sdd-momo-s3.s3.ap-northeast-2.amazonaws.com

  servlet:
    multipart:
      max-file-size: 10MB

management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true

info:
  app:
    name: sparta-deploy-demo
    version: 1.0.0
    memo: 1