spring:
  application:
    name: cloud-architecture-deploy-demo

  jpa:
    hibernate:
      ddl-auto: validate

management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true

info:
  app:
    name: sparta-deploy-demo
    version: 1.0.0
