name: Deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.png'
      - '**/*.jpg'

# OIDC 토큰 요청 권한
permissions:
  id-token: write   # OIDC 토큰 요청용
  contents: read    # 코드 체크아웃용 (체크아웃 - Repo에 있는 코드를 Runner에 옮김)

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      # Gradle 캐시
      - name: Cache Gradle packages
        uses: actions/cache@v5
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Test
        run: ./gradlew test

      - name: Build
        run: ./gradlew bootJar

      # cd 에서 업로드할 jar 파일 여기서 만들어놓음
      - name: Upload Jar artifact
        uses: actions/upload-artifact@v6
        with:
          name: 'app-jar'
          path: 'build/libs/app.jar'

  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Download JAR artifact       # ← ci job에서 빌드한 JAR 다운로드
        uses: actions/download-artifact@v6
        with:
          name: app-jar
          path: build/libs/

      - name: Metadata
        id: meta
        run: |
          echo "git_sha=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      # AWS 자격증명 - OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      # ECR 로그인
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Docker hub 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Docker 빌드 및 push
      - name: Build and push Docker image
        id: build_image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ steps.meta.outputs.git_sha }}
        run: |
          ECR_URI=$ECR_REGISTRY/${{ secrets.ECR_REPOSITORY }}
          DOCKERHUB_URI=${{ secrets.DOCKERHUB_USERNAME }}/cloud-architecture-deploy-demo

          # Docker 빌드
          docker build --platform linux/arm64 -t $ECR_URI:$IMAGE_TAG -t $DOCKERHUB_URI:$IMAGE_TAG .
          
          # push
          docker push $ECR_URI:$IMAGE_TAG
          docker push $DOCKERHUB_URI:$IMAGE_TAG
          
          # 결과 출력
          echo "✅ Pushed: $ECR_URI:$IMAGE_TAG"
          echo "✅ Pushed: $DOCKERHUB_URI:$IMAGE_TAG"

      - name: Deploy to EC2
        shell: bash
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ steps.meta.outputs.git_sha }}
        run: |
          set -euo pipefail

          ECR_URI=$ECR_REGISTRY/${{ secrets.ECR_REPOSITORY }}
          IMAGE_URI=$ECR_URI:$IMAGE_TAG
          
          cat > ssm-parameters.json <<EOF
          {
            "commands": [
              "set -euo pipefail",
        
              "aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin $ECR_REGISTRY",
              "docker pull $IMAGE_URI",
              "docker rm -f ${{ secrets.ECR_REPOSITORY }} 2>/dev/null || true",
              "docker run -d --name ${{ secrets.ECR_REPOSITORY }} --restart unless-stopped -p 8080:8080 $IMAGE_URI",
              "docker image prune -f",
              "docker ps --filter name=${{ secrets.ECR_REPOSITORY }}"
            ]
          }
          EOF
          
          COMMAND_ID=$(
            aws ssm send-command \
              --region "${{ secrets.AWS_REGION }}" \
              --instance-ids "${{ vars.AWS_INSTANCE_ID }}" \
              --document-name "AWS-RunShellScript" \
              --comment "Deploy ${{ env.IMAGE_TAG }}" \
              --parameters file://ssm-parameters.json \
              --timeout-seconds 600 \
              --query "Command.CommandId" \
              --output text
          )

          echo "SSM Command ID: ${COMMAND_ID}"
          
          aws ssm wait command-executed --command-id "$COMMAND_ID" --instance-id "${{ vars.AWS_INSTANCE_ID }}"